### ISSUE TITLE
import fails on loading empty module

### ISSUE THREAD

**Issue by noteflakes** [digital-fabric/modulation#6]
Backtrace:

```
Traceback (most recent call last):
        8: from bin/monocrono-writer:9:in `<main>'
        7: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/ext.rb:12:in `import'
        6: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/core.rb:43:in `import'
        5: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/core.rb:103:in `create_module_from_file'
        4: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/builder.rb:17:in `make'
        3: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/builder.rb:47:in `track_module_dependencies'
        2: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/builder.rb:21:in `block in make'
        1: from /home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/builder.rb:58:in `load_module_code'
/home/ec2-user/.rvm/gems/ruby-2.6.5/gems/modulation-1.0/lib/modulation/builder.rb:58:in `instance_eval': no implicit conversion of nil into String (TypeError)
```

**Comment by noteflakes** [comment]
Related to a problem with the `IO.read` patch in Polyphony, got nothing to do with Modulation.
